/**
 * content:自动投资首页
 * author: 王海波
 * createDate: 2017-11-30
 */


/* 自动投资首页 */
const AUTO_INVESTMENT_HOME_CHECK = 'AUTO_INVESTMENT_HOME_CHECK'

const AUTO_INVESTMENT_HOME_INFO = 'AUTO_INVESTMENT_HOME_INFO'

/* 自动投资说明 */
const AUTO_INVESTMENT_EXPLAIN = 'AUTO_INVESTMENT_EXPLAIN'

/* 获取使用红包投资信息 */
const AUTO_INVESTMENT_RED_PACKET = 'AUTO_INVESTMENT_RED_PACKET'

/* 获取使用余额投资信息 */
const AUTO_INVESTMENT_BALANCE = 'AUTO_INVESTMENT_BALANCE'

/* 获取投资记录信息 */
const AUTO_INVESTMENT_LOG = 'AUTO_INVESTMENT_LOG'

/* 获取用户服务信息 */
const AUTO_INVESTMENT_SERVICE = 'AUTO_INVESTMENT_SERVICE'

export {
  AUTO_INVESTMENT_HOME_CHECK,
  AUTO_INVESTMENT_HOME_INFO,
  AUTO_INVESTMENT_EXPLAIN,
  AUTO_INVESTMENT_RED_PACKET,
  AUTO_INVESTMENT_BALANCE,
  AUTO_INVESTMENT_LOG,
  AUTO_INVESTMENT_SERVICE
}
